<a href="https://colab.research.google.com/github/WooJungE/About_data/blob/main/20230323.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
robots = [[24, 23680], [35, ], [46, 47350], [27, ]]
data = pd.DataFrame(robots, columns=['max_speed', 'price'])
print(data)

   max_speed    price
0         24  23680.0
1         35      NaN
2         46  47350.0
3         27      NaN


In [2]:
data.dropna(subset=['price'], axis=0, inplace=True)
print(data)

   max_speed    price
0         24  23680.0
2         46  47350.0


In [3]:
data = pd.DataFrame(robots, columns=['max_speed', 'price'])
mean = data['price'].mean()
data.replace(np.NaN, mean, inplace=True)
print(data)

   max_speed    price
0         24  23680.0
1         35  35515.0
2         46  47350.0
3         27  35515.0


In [7]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/data/실습에 사용되는 파일2-20230314/iris_missing_values.csv')
df.index.name = 'record'
print(df.head())

        sepal length in cm  sepal width in cm  petal length in cm  \
record                                                              
0                      NaN                3.5                 1.4   
1                      4.9                3.0                 1.4   
2                      NaN                3.2                 1.3   
3                      4.6                3.1                 1.5   
4                      5.0                3.6                 1.4   

        petal width in cm species  
record                             
0                     0.2  setosa  
1                     0.2  setosa  
2                     0.2  setosa  
3                     0.2  setosa  
4                     0.2  setosa  


In [8]:
df['sepal length in cm'].isnull()
print(df['sepal length in cm'].isnull().values.any())
print(df['sepal length in cm'].isnull().values.sum())

True
6


In [9]:
df_example = df['sepal length in cm'].fillna('example')
print(df_example.head())

record
0    example
1        4.9
2    example
3        4.6
4        5.0
Name: sepal length in cm, dtype: object


In [10]:
df_dropped = df.dropna(axis=0)
print(df_dropped.head())

        sepal length in cm  sepal width in cm  petal length in cm  \
record                                                              
1                      4.9                3.0                 1.4   
3                      4.6                3.1                 1.5   
4                      5.0                3.6                 1.4   
6                      4.6                3.4                 1.4   
7                      5.0                3.4                 1.5   

        petal width in cm species  
record                             
1                     0.2  setosa  
3                     0.2  setosa  
4                     0.2  setosa  
6                     0.3  setosa  
7                     0.2  setosa  


In [11]:
df_dropped = df.dropna(axis=1)
print(df_dropped.head())

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]


In [12]:
from sklearn.impute import SimpleImputer
import numpy as n
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
cols=['sepal length in cm',
      'sepal width in cm',
      'petal length in cm',
      'petal width in cm',]

In [13]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/data/실습에 사용되는 파일2-20230314/iris_missing_values.csv')
df.index.name = 'record'
print(df.head())

        sepal length in cm  sepal width in cm  petal length in cm  \
record                                                              
0                      NaN                3.5                 1.4   
1                      4.9                3.0                 1.4   
2                      NaN                3.2                 1.3   
3                      4.6                3.1                 1.5   
4                      5.0                3.6                 1.4   

        petal width in cm species  
record                             
0                     0.2  setosa  
1                     0.2  setosa  
2                     0.2  setosa  
3                     0.2  setosa  
4                     0.2  setosa  


In [14]:
out_imp = imputer.fit_transform(df[cols])
df_new = pd.DataFrame(data = out_imp, columns = cols)
df_new = pd.concat([df_new, df[['species']]], axis = 1)
print(df_new.head())

   sepal length in cm  sepal width in cm  petal length in cm  \
0            5.870139                3.5                 1.4   
1            4.900000                3.0                 1.4   
2            5.870139                3.2                 1.3   
3            4.600000                3.1                 1.5   
4            5.000000                3.6                 1.4   

   petal width in cm species  
0                0.2  setosa  
1                0.2  setosa  
2                0.2  setosa  
3                0.2  setosa  
4                0.2  setosa  


In [15]:
price = np.random.randint(100, size=8)*10000
cars = pd.DataFrame(price, columns=['price'])
cars

price
0  170000
1  690000
2  420000
3  520000
4  340000
5  780000
6  540000
7  650000

In [17]:
group_names = ['low', 'mid', 'high']
cars['level'], mybin = pd.cut(cars['price'], 3, labels = group_names, retbins=True)
cars

price level
0  170000   low
1  690000  high
2  420000   mid
3  520000   mid
4  340000   low
5  780000  high
6  540000   mid
7  650000  high

In [18]:
mybin

array([169390.        , 373333.33333333, 576666.66666667, 780000.        ])

In [19]:
df = pd.read_csv("/content/drive/MyDrive/data/실습에 사용되는 파일2-20230314/iris.csv"); df.index.name = 'record'
cols = ['sepal length in cm',
        'sepal width in cm',
        'petal length in cm',
        'petal width in cm',]

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
out_scaled = scaler.fit_transform(df[cols])
print(out_scaled[:10])

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]]


In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
out_scaled = scaler.fit_transform(df[cols])
print(out_scaled[:10])

[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]
 [-0.53717756  1.95766909 -1.17067529 -1.05003079]
 [-1.50652052  0.80065426 -1.3412724  -1.18150376]
 [-1.02184904  0.80065426 -1.2844067  -1.31297673]
 [-1.74885626 -0.35636057 -1.3412724  -1.31297673]
 [-1.14301691  0.10644536 -1.2844067  -1.4444497 ]]


In [26]:
df = pd.read_csv("/content/drive/MyDrive/data/실습에 사용되는 파일2-20230314/long_jump.csv")
df.set_index('Person', inplace=True)

In [31]:
cats=['Jersey Size', 'Shoe Size']
print(df[cats])

         Jersey Size  Shoe Size
Person                         
Thomas           2.0        0.0
Jane             1.0        2.0
Vaughn           0.0        3.0
Vera             1.0        1.0
Vincent          0.0        3.0
Lei-Ann          2.0        0.0


In [32]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
out_enc = enc.fit_transform(df[cats])
print('identified categories:')
print(enc.categories_)
print('encoded data:')
print(out_enc)

identified categories:
[array([0., 1., 2.]), array([0., 1., 2., 3.])]
encoded data:
[[2. 0.]
 [1. 2.]
 [0. 3.]
 [1. 1.]
 [0. 3.]
 [2. 0.]]


In [33]:
df[cats] = out_enc
print(df.head())

         Age  Height  Weight  Training Hours/week Jersey Color  Jersey Size  \
Person                                                                        
Thomas    12    57.5    73.4                  6.5         blue          2.0   
Jane      13    65.5    85.3                  8.9        green          1.0   
Vaughn    17    71.9   125.9                  1.1        green          0.0   
Vera      14    65.3   100.5                  7.9          red          1.0   
Vincent   18    70.1   110.7                 10.5         blue          0.0   

         Shoe Size  Long Jump  
Person                         
Thomas         0.0       19.2  
Jane           2.0       25.1  
Vaughn         3.0       14.3  
Vera           1.0       18.3  
Vincent        3.0       21.1  


In [35]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse = False)
out_enc = enc.fit_transform(df[cats])
new_cols = enc.get_feature_names_out(cats).tolist()
print(new_cols)

['Jersey Size_0.0', 'Jersey Size_1.0', 'Jersey Size_2.0', 'Shoe Size_0.0', 'Shoe Size_1.0', 'Shoe Size_2.0', 'Shoe Size_3.0']


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [37]:
df_enc = pd.DataFrame(data = out_enc, columns = new_cols)
df_enc.index = df.index
df.drop(cats, axis = 1, inplace=True)
df = pd.concat([df, df_enc], axis = 1)
print(df.columns)

Index(['Age', 'Height', 'Weight', 'Training Hours/week', 'Jersey Color',
       'Long Jump', 'Jersey Size_0.0', 'Jersey Size_1.0', 'Jersey Size_2.0',
       'Shoe Size_0.0', 'Shoe Size_1.0', 'Shoe Size_2.0', 'Shoe Size_3.0'],
      dtype='object')


In [40]:
from sklearn import preprocessing
enc = preprocessing.LabelEncoder()
out_enc = enc.fit_transform([1, 2, 5, 2, 4, 2, 5])
print(out_enc)
out_enc = enc.fit_transform(["blue", "red", "blue", "green", "red", "red"])
print(out_enc)

[0 1 3 1 2 1 3]
[0 2 0 1 2 2]
